# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Rustのツールチェインと、Makefileで必要なコンポーネントをインストール
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # cargoの依存関係とビルド成果物をキャッシュして、将来の実行を高速化
      - name: Cache cargo registry and target directory
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Makefileの 'ci' ターゲットを実行
      - name: Run CI tasks via Makefile
        run: make ci