# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Rust CI
    runs-on: ubuntu-latest

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Rust CI (linux)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      # CI ではインクリメンタル無効の方が安定（キャッシュで十分高速）
      CARGO_INCREMENTAL: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # バージョン埋め込みや変更点チェックをする場合は 0 を推奨
          fetch-depth: 0

      # 推奨：Rust専用キャッシュ（~/.cargo/bin や target を良きに計らってくれる）
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # workspace: true が既定。複数クレートでもOK
          # cache-on-failure: true でも可
          cache-all-crates: true

      # Makefileの 'ci' ターゲットを実行
      - name: Run CI tasks via Makefile
        run: make ci